name: Build LogFacil

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          pip install pyinstaller
          pip install ttkbootstrap

      - name: Gerar executável
        run: |
          pyinstaller --onefile --noconsole logfacil.py

      - name: Criar Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.exe"
          tag: ${{ github.ref_name }}
